### ISSUE TITLE
Panic: State Transition Stage not found (assuming auto-added label)

### ISSUE THREAD

**Issue by Indy2222** [IyesGames/iyes_loopless#42]
After upgrade from 0.7 to 0.8 I started to get the following error:

```
thread 'main' panicked at 'State Transition Stage not found (assuming auto-added label)', /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/iyes_loopless-0.8.0/src/state.rs:343:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:1880:5
   5: core::option::Option<T>::expect
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:738:21
   6: <bevy_app::app::App as iyes_loopless::state::app::AppLooplessStateExt>::add_enter_system
             at /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/iyes_loopless-0.8.0/src/state.rs:343:25
   7: <de_menu::mainmenu::MainMenuPlugin as bevy_app::plugin::Plugin>::build
             at ./crates/menu/src/mainmenu.rs:16:9
   8: bevy_app::plugin_group::PluginGroupBuilder::finish
             at /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.8.1/src/plugin_group.rs:135:21
   9: bevy_app::app::App::add_plugins
             at /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.8.1/src/app.rs:810:9
  10: de_game::main
             at ./src/main.rs:27:5
  11: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Note that I do this in a plugin (which is executed first):

```rust
app.add_loopless_state(AppState::InMenu)
    .add_loopless_state(GameState::None);
```

and this in another plugin (which executes later):

```rust
app.add_enter_system(AppState::InMenu, setup)
    .add_exit_system(AppState::InMenu, cleanup)
```

**Comment by inodentry** [comment]
Could this be because you are adding the plugins via a PluginGroup?

**Comment by Indy2222** [comment]
Yes. Why is that a problem?

**Comment by Indy2222** [comment]
This is no longer happening after upgrade to `bevy = "0.9"` and `iyes_loopless = "0.9.1"`

**Comment by inodentry** [comment]
Awesome. I don't remember exactly what I did that could have fixed it, but I'm glad it is no longer a problem.

I'm closing the issue. Reopen if you think anything more needs to be done.
